a = int(input("Enter the First Number: "))
b = int(input("Enter the Second Number: "))
print('Addition of Two Numbers: ', a+b)
print("Subtraction of Two Numbers: ", a-b)
print("Multiplication of Two Numbers: ", a*b)
print("Division of Two Numbers: ", a/b)
print("Exponentiation of Two Numbers: ", a**b)
print("Floor Division of Two Numbers: ", a//b)
print("Modulus of Two Numbers: ", a%b)